# Copyright (C) 2026 Jamie Cui
# Author: Jamie Cui
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "bilive-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
bilive-core = { path = "../bilive-core" }
futures-util.workspace = true
mime_guess.workspace = true
qrcode.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
